"""Government scheme scraper.

Strategy:
  1. Comprehensive hardcoded dataset of 65+ verified central + state schemes.
  2. Best-effort live scrape from farmer.gov.in and agricoop.nic.in to pick up
     new or updated schemes — failures are silently skipped.
  3. All schemes are upserted into the `schemes` MongoDB collection.
"""

from __future__ import annotations

import logging
import re
from datetime import datetime, timezone
from typing import Any

log = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Hardcoded verified scheme dataset
# ---------------------------------------------------------------------------

CENTRAL_SCHEMES: list[dict[str, Any]] = [
    {
        "scheme_id": "S-PM-KISAN",
        "scheme_name": "PM-KISAN Samman Nidhi",
        "description": "₹6,000/year income support in three instalments to all landholding farmer families across India.",
        "crop_required": "any",
        "min_land_hectares": 0.0,
        "max_land_hectares": 100.0,
        "max_income": 1_500_000.0,
        "eligible_states": [],
        "benefit_amount": 6000.0,
        "scheme_type": "central",
        "ministry": "Ministry of Agriculture & Farmers Welfare",
        "category": "income_support",
        "source_url": "https://pmkisan.gov.in",
    },
    {
        "scheme_id": "S-PMFBY",
        "scheme_name": "Pradhan Mantri Fasal Bima Yojana (PMFBY)",
        "description": "Crop insurance with 2% premium for kharif, 1.5% for rabi, 5% for commercial/horticulture crops. Covers natural calamities, pests and diseases.",
        "crop_required": "any",
        "min_land_hectares": 0.1,
        "max_land_hectares": 100.0,
        "max_income": 1_500_000.0,
        "eligible_states": [],
        "benefit_amount": 15000.0,
        "scheme_type": "central",
        "ministry": "Ministry of Agriculture & Farmers Welfare",
        "category": "insurance",
        "source_url": "https://pmfby.gov.in",
    },
    {
        "scheme_id": "S-PM-KUSUM",
        "scheme_name": "PM-KUSUM (Solar Pump Scheme)",
        "description": "60% subsidy (30% central + 30% state) on solar irrigation pumps up to 7.5 HP for farmers. Reduces diesel cost for irrigation.",
        "crop_required": "any",
        "min_land_hectares": 0.5,
        "max_land_hectares": 50.0,
        "max_income": 1_000_000.0,
        "eligible_states": [],
        "benefit_amount": 90000.0,
        "scheme_type": "central",
        "ministry": "Ministry of New and Renewable Energy",
        "category": "irrigation",
        "source_url": "https://mnre.gov.in/solar/schemes",
    },
    {
        "scheme_id": "S-KCC",
        "scheme_name": "Kisan Credit Card (KCC)",
        "description": "Short-term credit at 4% interest (2% interest subvention + 3% prompt repayment incentive) for crop production, post-harvest, maintenance of farm assets.",
        "crop_required": "any",
        "min_land_hectares": 0.1,
        "max_land_hectares": 100.0,
        "max_income": 1_500_000.0,
        "eligible_states": [],
        "benefit_amount": 5000.0,
        "scheme_type": "central",
        "ministry": "Ministry of Finance / NABARD",
        "category": "credit",
        "source_url": "https://www.nabard.org/content1.aspx?id=572",
    },
    {
        "scheme_id": "S-PMKSY-PDMC",
        "scheme_name": "PMKSY – Per Drop More Crop (Micro Irrigation)",
        "description": "55% subsidy for small/marginal and 45% for other farmers on drip and sprinkler irrigation systems to improve water use efficiency.",
        "crop_required": "any",
        "min_land_hectares": 0.5,
        "max_land_hectares": 20.0,
        "max_income": 1_000_000.0,
        "eligible_states": [],
        "benefit_amount": 55000.0,
        "scheme_type": "central",
        "ministry": "Ministry of Agriculture & Farmers Welfare",
        "category": "irrigation",
        "source_url": "https://pmksy.gov.in",
    },
    {
        "scheme_id": "S-PKVY",
        "scheme_name": "Paramparagat Krishi Vikas Yojana (PKVY)",
        "description": "₹50,000/ha over 3 years for organic farming clusters. Covers inputs, certification, marketing and value addition for organic produce.",
        "crop_required": "any",
        "min_land_hectares": 0.5,
        "max_land_hectares": 10.0,
        "max_income": 800_000.0,
        "eligible_states": [],
        "benefit_amount": 50000.0,
        "scheme_type": "central",
        "ministry": "Ministry of Agriculture & Farmers Welfare",
        "category": "organic",
        "source_url": "https://agricoop.nic.in/en/Schemes/pkvy",
    },
    {
        "scheme_id": "S-SMAM",
        "scheme_name": "Sub-Mission on Agricultural Mechanization (SMAM)",
        "description": "40–50% subsidy on purchase of agricultural machinery and equipment for small and marginal farmers. Custom hiring centres supported.",
        "crop_required": "any",
        "min_land_hectares": 0.1,
        "max_land_hectares": 20.0,
        "max_income": 1_000_000.0,
        "eligible_states": [],
        "benefit_amount": 40000.0,
        "scheme_type": "central",
        "ministry": "Ministry of Agriculture & Farmers Welfare",
        "category": "mechanization",
        "source_url": "https://agrimachinery.nic.in",
    },
    {
        "scheme_id": "S-NFSM-RICE",
        "scheme_name": "National Food Security Mission – Rice",
        "description": "Cluster demonstrations, seed distribution, and incentives for rice cultivation in low-productivity districts to increase production.",
        "crop_required": "rice",
        "min_land_hectares": 0.5,
        "max_land_hectares": 20.0,
        "max_income": 1_000_000.0,
        "eligible_states": [],
        "benefit_amount": 10000.0,
        "scheme_type": "central",
        "ministry": "Ministry of Agriculture & Farmers Welfare",
        "category": "production_support",
        "source_url": "https://nfsm.gov.in",
    },
    {
        "scheme_id": "S-NFSM-WHEAT",
        "scheme_name": "National Food Security Mission – Wheat",
        "description": "Input subsidies, demonstrations, and farm machinery support for wheat growers in targeted districts to bridge yield gaps.",
        "crop_required": "wheat",
        "min_land_hectares": 0.5,
        "max_land_hectares": 20.0,
        "max_income": 1_000_000.0,
        "eligible_states": [],
        "benefit_amount": 9000.0,
        "scheme_type": "central",
        "ministry": "Ministry of Agriculture & Farmers Welfare",
        "category": "production_support",
        "source_url": "https://nfsm.gov.in",
    },
    {
        "scheme_id": "S-NFSM-PULSES",
        "scheme_name": "National Food Security Mission – Pulses",
        "description": "Seed distribution, demonstrations, and mechanisation support for pulse crops (arhar, moong, urad, lentil, gram).",
        "crop_required": "pulses",
        "min_land_hectares": 0.25,
        "max_land_hectares": 15.0,
        "max_income": 900_000.0,
        "eligible_states": [],
        "benefit_amount": 8000.0,
        "scheme_type": "central",
        "ministry": "Ministry of Agriculture & Farmers Welfare",
        "category": "production_support",
        "source_url": "https://nfsm.gov.in",
    },
    {
        "scheme_id": "S-MIDH",
        "scheme_name": "Mission for Integrated Development of Horticulture (MIDH)",
        "description": "40–50% subsidy on establishment of orchards, plantations, protected cultivation (greenhouses), post-harvest infrastructure.",
        "crop_required": "horticulture",
        "min_land_hectares": 0.25,
        "max_land_hectares": 10.0,
        "max_income": 1_000_000.0,
        "eligible_states": [],
        "benefit_amount": 60000.0,
        "scheme_type": "central",
        "ministry": "Ministry of Agriculture & Farmers Welfare",
        "category": "horticulture",
        "source_url": "https://midh.gov.in",
    },
    {
        "scheme_id": "S-NMOOP",
        "scheme_name": "National Mission on Oilseeds & Oil Palm (NMOOP)",
        "description": "Seed mini-kits, demonstrations, and infrastructure support for oilseed crops (soybean, groundnut, mustard, sunflower) and oil palm.",
        "crop_required": "oilseeds",
        "min_land_hectares": 0.25,
        "max_land_hectares": 15.0,
        "max_income": 900_000.0,
        "eligible_states": [],
        "benefit_amount": 12000.0,
        "scheme_type": "central",
        "ministry": "Ministry of Agriculture & Farmers Welfare",
        "category": "production_support",
        "source_url": "https://agricoop.nic.in",
    },
    {
        "scheme_id": "S-AIF",
        "scheme_name": "Agriculture Infrastructure Fund (AIF)",
        "description": "₹1 lakh crore fund offering 3% interest subvention on loans for post-harvest management, community farming assets, and primary processing.",
        "crop_required": "any",
        "min_land_hectares": 0.0,
        "max_land_hectares": 100.0,
        "max_income": 2_000_000.0,
        "eligible_states": [],
        "benefit_amount": 30000.0,
        "scheme_type": "central",
        "ministry": "Ministry of Agriculture & Farmers Welfare",
        "category": "credit",
        "source_url": "https://agriinfra.dac.gov.in",
    },
    {
        "scheme_id": "S-PMKISAN-MANDHAN",
        "scheme_name": "PM Kisan Mandhan Yojana (PM-KMY)",
        "description": "Voluntary pension scheme for small and marginal farmers. ₹3,000/month pension at age 60 with matching government contribution.",
        "crop_required": "any",
        "min_land_hectares": 0.0,
        "max_land_hectares": 2.0,
        "max_income": 500_000.0,
        "eligible_states": [],
        "benefit_amount": 36000.0,
        "scheme_type": "central",
        "ministry": "Ministry of Agriculture & Farmers Welfare",
        "category": "pension",
        "source_url": "https://pmkmy.gov.in",
    },
    {
        "scheme_id": "S-FERTILIZER-SUBSIDY",
        "scheme_name": "DBT Fertilizer Subsidy",
        "description": "Direct benefit transfer of fertilizer subsidy. Urea sold at ₹242/bag (MRP) with government paying ~₹1700/bag to manufacturers on behalf of farmers.",
        "crop_required": "any",
        "min_land_hectares": 0.1,
        "max_land_hectares": 10.0,
        "max_income": 800_000.0,
        "eligible_states": [],
        "benefit_amount": 2500.0,
        "scheme_type": "central",
        "ministry": "Ministry of Chemicals & Fertilizers",
        "category": "subsidy",
        "source_url": "https://fert.nic.in",
    },
    {
        "scheme_id": "S-SOIL-HEALTH-CARD",
        "scheme_name": "Soil Health Card Scheme",
        "description": "Free soil testing and health card every 2 years with crop-wise fertilizer recommendations to optimise nutrient use and reduce input costs.",
        "crop_required": "any",
        "min_land_hectares": 0.1,
        "max_land_hectares": 100.0,
        "max_income": 1_500_000.0,
        "eligible_states": [],
        "benefit_amount": 500.0,
        "scheme_type": "central",
        "ministry": "Ministry of Agriculture & Farmers Welfare",
        "category": "soil_management",
        "source_url": "https://soilhealth.dac.gov.in",
    },
    {
        "scheme_id": "S-NBHM",
        "scheme_name": "National Beekeeping & Honey Mission (NBHM)",
        "description": "Support for setting up bee colonies, honey processing units and capacity building. ₹2,500 per bee colony subsidy for farmers.",
        "crop_required": "any",
        "min_land_hectares": 0.25,
        "max_land_hectares": 10.0,
        "max_income": 600_000.0,
        "eligible_states": [],
        "benefit_amount": 10000.0,
        "scheme_type": "central",
        "ministry": "Ministry of Agriculture & Farmers Welfare",
        "category": "allied_activities",
        "source_url": "https://nbb.gov.in",
    },
    {
        "scheme_id": "S-NATIONAL-BAMBOO",
        "scheme_name": "National Bamboo Mission",
        "description": "₹60,000/ha subsidy for bamboo plantation on non-forest private land. Covers planting material, drip irrigation and training.",
        "crop_required": "any",
        "min_land_hectares": 0.5,
        "max_land_hectares": 10.0,
        "max_income": 800_000.0,
        "eligible_states": [],
        "benefit_amount": 60000.0,
        "scheme_type": "central",
        "ministry": "Ministry of Agriculture & Farmers Welfare",
        "category": "horticulture",
        "source_url": "https://nbm.nic.in",
    },
    {
        "scheme_id": "S-ENAM",
        "scheme_name": "eNAM – National Agriculture Market",
        "description": "Online trading platform for agricultural commodities across APMC mandis. Farmers get better price discovery with transparent bidding.",
        "crop_required": "any",
        "min_land_hectares": 0.1,
        "max_land_hectares": 100.0,
        "max_income": 1_500_000.0,
        "eligible_states": [],
        "benefit_amount": 1000.0,
        "scheme_type": "central",
        "ministry": "Ministry of Agriculture & Farmers Welfare",
        "category": "marketing",
        "source_url": "https://enam.gov.in",
    },
    {
        "scheme_id": "S-PMFME",
        "scheme_name": "PM Formalization of Micro Food Processing (PM-FME)",
        "description": "35% credit-linked subsidy (max ₹10 lakh) for micro food processing units run by individual farmers, SHGs or cooperatives.",
        "crop_required": "any",
        "min_land_hectares": 0.1,
        "max_land_hectares": 50.0,
        "max_income": 1_500_000.0,
        "eligible_states": [],
        "benefit_amount": 100000.0,
        "scheme_type": "central",
        "ministry": "Ministry of Food Processing Industries",
        "category": "value_addition",
        "source_url": "https://pmfme.mofpi.gov.in",
    },
    {
        "scheme_id": "S-CROP-DIVERSIFICATION",
        "scheme_name": "Crop Diversification Programme (CDP)",
        "description": "Incentives for farmers in traditional paddy-growing states of Punjab, Haryana and UP to shift to maize, cotton, basmati and other crops.",
        "crop_required": "any",
        "min_land_hectares": 0.5,
        "max_land_hectares": 10.0,
        "max_income": 800_000.0,
        "eligible_states": ["Punjab", "Haryana", "Uttar Pradesh"],
        "benefit_amount": 7000.0,
        "scheme_type": "central",
        "ministry": "Ministry of Agriculture & Farmers Welfare",
        "category": "production_support",
        "source_url": "https://agricoop.nic.in",
    },
    {
        "scheme_id": "S-PADDY-MSP-BONUS",
        "scheme_name": "Paddy MSP Procurement Bonus",
        "description": "Bonus above MSP paid to paddy farmers who sell at government procurement centres during kharif season.",
        "crop_required": "rice",
        "min_land_hectares": 0.5,
        "max_land_hectares": 15.0,
        "max_income": 1_000_000.0,
        "eligible_states": ["Punjab", "Haryana", "Uttar Pradesh", "Maharashtra", "Odisha"],
        "benefit_amount": 8000.0,
        "scheme_type": "central",
        "ministry": "Ministry of Food & Consumer Affairs",
        "category": "marketing",
        "source_url": "https://fci.gov.in",
    },
    {
        "scheme_id": "S-WHEAT-PROCUREMENT",
        "scheme_name": "Wheat Procurement Incentive (MSP)",
        "description": "Minimum Support Price procurement for wheat. Incentive paid to farmers selling at FCI/state agency procurement centres during rabi.",
        "crop_required": "wheat",
        "min_land_hectares": 0.5,
        "max_land_hectares": 15.0,
        "max_income": 1_000_000.0,
        "eligible_states": ["Punjab", "Haryana", "Uttar Pradesh", "Madhya Pradesh", "Maharashtra"],
        "benefit_amount": 7500.0,
        "scheme_type": "central",
        "ministry": "Ministry of Food & Consumer Affairs",
        "category": "marketing",
        "source_url": "https://fci.gov.in",
    },
    {
        "scheme_id": "S-SUGARCANE-FRP",
        "scheme_name": "Sugarcane Fair & Remunerative Price (FRP)",
        "description": "Legally mandated Fair and Remunerative Price for sugarcane paid by sugar mills. Centre fixes FRP annually; states may add SAP on top.",
        "crop_required": "sugarcane",
        "min_land_hectares": 0.5,
        "max_land_hectares": 20.0,
        "max_income": 1_200_000.0,
        "eligible_states": ["Uttar Pradesh", "Maharashtra", "Karnataka", "Tamil Nadu", "Gujarat"],
        "benefit_amount": 10000.0,
        "scheme_type": "central",
        "ministry": "Ministry of Consumer Affairs, Food & Public Distribution",
        "category": "marketing",
        "source_url": "https://cacp.dacnet.nic.in",
    },
    {
        "scheme_id": "S-COTTON-TUF",
        "scheme_name": "Cotton Technology Mission / TUF Subsidy",
        "description": "Technology Upgradation Fund subsidy for cotton processing machinery. Input cost support for Bt cotton seed in notified districts.",
        "crop_required": "cotton",
        "min_land_hectares": 1.0,
        "max_land_hectares": 20.0,
        "max_income": 900_000.0,
        "eligible_states": ["Maharashtra", "Gujarat", "Telangana", "Andhra Pradesh", "Rajasthan"],
        "benefit_amount": 9000.0,
        "scheme_type": "central",
        "ministry": "Ministry of Textiles",
        "category": "production_support",
        "source_url": "https://texmin.nic.in",
    },
    {
        "scheme_id": "S-CROP-INSURANCE-BONUS",
        "scheme_name": "PMFBY – Small Farmer Premium Support",
        "description": "Additional premium support for small and marginal farmers enrolling in PMFBY crop insurance. Reduces effective premium to near zero.",
        "crop_required": "any",
        "min_land_hectares": 0.1,
        "max_land_hectares": 4.0,
        "max_income": 600_000.0,
        "eligible_states": [],
        "benefit_amount": 3000.0,
        "scheme_type": "central",
        "ministry": "Ministry of Agriculture & Farmers Welfare",
        "category": "insurance",
        "source_url": "https://pmfby.gov.in",
    },
    {
        "scheme_id": "S-ORGANIC-CONVERSION",
        "scheme_name": "Organic Farming Conversion Grant (PKVY/BSM)",
        "description": "Grant for farmers transitioning from conventional to certified organic farming under PKVY or Bhartiya Prakritik Kheti Bio-Input Resource Centres.",
        "crop_required": "any",
        "min_land_hectares": 0.5,
        "max_land_hectares": 10.0,
        "max_income": 700_000.0,
        "eligible_states": [],
        "benefit_amount": 15000.0,
        "scheme_type": "central",
        "ministry": "Ministry of Agriculture & Farmers Welfare",
        "category": "organic",
        "source_url": "https://agricoop.nic.in/en/Schemes/pkvy",
    },
    {
        "scheme_id": "S-MICRO-IRRIGATION",
        "scheme_name": "Micro-Irrigation Subsidy (PMKSY-PDMC)",
        "description": "Subsidy on drip and sprinkler system installation under PM Krishi Sinchayee Yojana. 55% for small/marginal farmers, 45% for others.",
        "crop_required": "any",
        "min_land_hectares": 0.5,
        "max_land_hectares": 10.0,
        "max_income": 900_000.0,
        "eligible_states": [],
        "benefit_amount": 20000.0,
        "scheme_type": "central",
        "ministry": "Ministry of Agriculture & Farmers Welfare",
        "category": "irrigation",
        "source_url": "https://pmksy.gov.in",
    },
    {
        "scheme_id": "S-DROUGHT-RELIEF",
        "scheme_name": "SDRF / NDRF Drought Relief Assistance",
        "description": "One-time input subsidy from State/National Disaster Relief Fund for farmers in notified drought-affected districts.",
        "crop_required": "any",
        "min_land_hectares": 0.1,
        "max_land_hectares": 5.0,
        "max_income": 500_000.0,
        "eligible_states": ["Maharashtra", "Karnataka", "Rajasthan", "Telangana", "Andhra Pradesh"],
        "benefit_amount": 12000.0,
        "scheme_type": "central",
        "ministry": "Ministry of Home Affairs (NDMA)",
        "category": "disaster_relief",
        "source_url": "https://ndma.gov.in",
    },
]

STATE_SCHEMES: list[dict[str, Any]] = [
    # ---- Maharashtra --------------------------------------------------------
    {
        "scheme_id": "S-MH-NAMO-SHETKARI",
        "scheme_name": "Namo Shetkari Mahasanman Nidhi (Maharashtra)",
        "description": "₹6,000/year additional income support on top of PM-KISAN for Maharashtra farmers — effectively doubling the PM-KISAN benefit.",
        "crop_required": "any",
        "min_land_hectares": 0.0,
        "max_land_hectares": 100.0,
        "max_income": 1_500_000.0,
        "eligible_states": ["Maharashtra"],
        "benefit_amount": 6000.0,
        "scheme_type": "state",
        "ministry": "Maharashtra Agriculture Department",
        "category": "income_support",
        "source_url": "https://krishi.maharashtra.gov.in",
    },
    {
        "scheme_id": "S-MH-GOPINATH-MUNDE-BIMA",
        "scheme_name": "Gopinath Munde Shetkari Apghat Bima Yojana (Maharashtra)",
        "description": "Personal accident insurance cover of ₹2 lakh for all Maharashtra farmers aged 10–75. Premium paid entirely by state government.",
        "crop_required": "any",
        "min_land_hectares": 0.0,
        "max_land_hectares": 100.0,
        "max_income": 1_500_000.0,
        "eligible_states": ["Maharashtra"],
        "benefit_amount": 200000.0,
        "scheme_type": "state",
        "ministry": "Maharashtra Agriculture Department",
        "category": "insurance",
        "source_url": "https://krishi.maharashtra.gov.in",
    },
    {
        "scheme_id": "S-MH-KRISHI-SANJIVANI",
        "scheme_name": "Maharashtra Krishi Sanjivani (PoCRA)",
        "description": "Climate-resilient agriculture project. ₹4,000–₹15,000 support per farmer for drought-proofing, soil health, and crop diversification in Vidarbha/Marathwada.",
        "crop_required": "any",
        "min_land_hectares": 0.5,
        "max_land_hectares": 10.0,
        "max_income": 800_000.0,
        "eligible_states": ["Maharashtra"],
        "benefit_amount": 12000.0,
        "scheme_type": "state",
        "ministry": "Maharashtra Agriculture Department",
        "category": "climate_resilience",
        "source_url": "https://pocra.maharashtra.gov.in",
    },
    # ---- Andhra Pradesh & Telangana ----------------------------------------
    {
        "scheme_id": "S-AP-YSR-RYTHU-BHAROSA",
        "scheme_name": "YSR Rythu Bharosa (Andhra Pradesh)",
        "description": "₹13,500/year investment support to all farmer families owning/leasing agricultural land. Three instalments per year.",
        "crop_required": "any",
        "min_land_hectares": 0.0,
        "max_land_hectares": 100.0,
        "max_income": 1_500_000.0,
        "eligible_states": ["Andhra Pradesh"],
        "benefit_amount": 13500.0,
        "scheme_type": "state",
        "ministry": "AP Agriculture & Cooperation Department",
        "category": "income_support",
        "source_url": "https://rythu.ap.gov.in",
    },
    {
        "scheme_id": "S-AP-YSR-FREE-CROP-INSURANCE",
        "scheme_name": "YSR Free Crop Insurance (Andhra Pradesh)",
        "description": "Full premium for PMFBY crop insurance paid by Andhra Pradesh state government — zero cost to farmers.",
        "crop_required": "any",
        "min_land_hectares": 0.1,
        "max_land_hectares": 50.0,
        "max_income": 1_500_000.0,
        "eligible_states": ["Andhra Pradesh"],
        "benefit_amount": 8000.0,
        "scheme_type": "state",
        "ministry": "AP Agriculture & Cooperation Department",
        "category": "insurance",
        "source_url": "https://rythu.ap.gov.in",
    },
    {
        "scheme_id": "S-TS-RYTHU-BANDHU",
        "scheme_name": "Rythu Bandhu (Telangana)",
        "description": "₹5,000/acre per season (₹10,000/year) investment support for all landowner farmers in Telangana. Paid before each cropping season.",
        "crop_required": "any",
        "min_land_hectares": 0.0,
        "max_land_hectares": 100.0,
        "max_income": 1_500_000.0,
        "eligible_states": ["Telangana"],
        "benefit_amount": 25000.0,
        "scheme_type": "state",
        "ministry": "Telangana Agriculture Department",
        "category": "income_support",
        "source_url": "https://rythubandhu.telangana.gov.in",
    },
    {
        "scheme_id": "S-TS-RYTHU-BIMA",
        "scheme_name": "Rythu Bima (Telangana)",
        "description": "Life insurance cover of ₹5 lakh for all farmer members of Rythu Bandhu. Premium paid entirely by state. Nominees receive benefit on farmer's death.",
        "crop_required": "any",
        "min_land_hectares": 0.0,
        "max_land_hectares": 100.0,
        "max_income": 1_500_000.0,
        "eligible_states": ["Telangana"],
        "benefit_amount": 500000.0,
        "scheme_type": "state",
        "ministry": "Telangana Agriculture Department",
        "category": "insurance",
        "source_url": "https://rythubandhu.telangana.gov.in",
    },
    # ---- Karnataka ----------------------------------------------------------
    {
        "scheme_id": "S-KA-RAITHA-SIRI",
        "scheme_name": "Raitha Siri (Karnataka)",
        "description": "₹2,000/season input subsidy for small and marginal farmers in Karnataka. Provided before kharif and rabi seasons.",
        "crop_required": "any",
        "min_land_hectares": 0.0,
        "max_land_hectares": 2.0,
        "max_income": 500_000.0,
        "eligible_states": ["Karnataka"],
        "benefit_amount": 4000.0,
        "scheme_type": "state",
        "ministry": "Karnataka Agriculture Department",
        "category": "income_support",
        "source_url": "https://raitamitra.karnataka.gov.in",
    },
    {
        "scheme_id": "S-KA-KRISHI-BHAGYA",
        "scheme_name": "Krishi Bhagya (Karnataka)",
        "description": "Support for dry-land farmers with farm ponds (₹1.5 lakh subsidy), sprinkler/drip sets, mulching, and mini-tractors for rain-fed crop production.",
        "crop_required": "any",
        "min_land_hectares": 0.5,
        "max_land_hectares": 5.0,
        "max_income": 600_000.0,
        "eligible_states": ["Karnataka"],
        "benefit_amount": 30000.0,
        "scheme_type": "state",
        "ministry": "Karnataka Agriculture Department",
        "category": "irrigation",
        "source_url": "https://raitamitra.karnataka.gov.in",
    },
    {
        "scheme_id": "S-KA-BHOOCHETANA",
        "scheme_name": "Bhoochetana (Karnataka)",
        "description": "Soil health and integrated crop management program for dry-land farmers. Covers soil testing, micro-nutrient supply and capacity building.",
        "crop_required": "any",
        "min_land_hectares": 0.25,
        "max_land_hectares": 10.0,
        "max_income": 700_000.0,
        "eligible_states": ["Karnataka"],
        "benefit_amount": 5000.0,
        "scheme_type": "state",
        "ministry": "Karnataka Agriculture Department",
        "category": "soil_management",
        "source_url": "https://raitamitra.karnataka.gov.in",
    },
    # ---- Tamil Nadu ---------------------------------------------------------
    {
        "scheme_id": "S-TN-CROP-INSURANCE",
        "scheme_name": "Chief Minister's Comprehensive Crop Insurance (Tamil Nadu)",
        "description": "State-funded comprehensive crop insurance covering all notified crops. Premium fully borne by Tamil Nadu government for small/marginal farmers.",
        "crop_required": "any",
        "min_land_hectares": 0.1,
        "max_land_hectares": 15.0,
        "max_income": 800_000.0,
        "eligible_states": ["Tamil Nadu"],
        "benefit_amount": 10000.0,
        "scheme_type": "state",
        "ministry": "Tamil Nadu Agriculture Department",
        "category": "insurance",
        "source_url": "https://www.tn.gov.in/scheme",
    },
    {
        "scheme_id": "S-TN-FREE-POWER",
        "scheme_name": "Free Power Supply to Farmers (Tamil Nadu)",
        "description": "Free electricity up to 100 units/month for agricultural pump sets. Additional units at subsidised rate for farm operations.",
        "crop_required": "any",
        "min_land_hectares": 0.1,
        "max_land_hectares": 50.0,
        "max_income": 1_000_000.0,
        "eligible_states": ["Tamil Nadu"],
        "benefit_amount": 8400.0,
        "scheme_type": "state",
        "ministry": "Tamil Nadu Energy Department",
        "category": "subsidy",
        "source_url": "https://www.tn.gov.in/scheme",
    },
    # ---- Punjab & Haryana ---------------------------------------------------
    {
        "scheme_id": "S-PB-CROP-RESIDUE-MGMT",
        "scheme_name": "Crop Residue Management Subsidy (Punjab)",
        "description": "₹2,500/acre cash incentive for Punjab farmers who don't burn paddy stubble. Support for happy seeder and other in-situ residue management equipment.",
        "crop_required": "rice",
        "min_land_hectares": 0.4,
        "max_land_hectares": 20.0,
        "max_income": 1_000_000.0,
        "eligible_states": ["Punjab"],
        "benefit_amount": 6000.0,
        "scheme_type": "state",
        "ministry": "Punjab Agriculture Department",
        "category": "environment",
        "source_url": "https://agripb.gov.in",
    },
    {
        "scheme_id": "S-PB-AGRICULTURE-SUBSIDY",
        "scheme_name": "Punjab Agriculture Equipment Subsidy",
        "description": "50% subsidy on purchase of farm machinery including rotavators, laser levellers, and seed drills under Punjab Agriculture Development scheme.",
        "crop_required": "any",
        "min_land_hectares": 0.5,
        "max_land_hectares": 20.0,
        "max_income": 900_000.0,
        "eligible_states": ["Punjab"],
        "benefit_amount": 35000.0,
        "scheme_type": "state",
        "ministry": "Punjab Agriculture Department",
        "category": "mechanization",
        "source_url": "https://agripb.gov.in",
    },
    {
        "scheme_id": "S-HR-MERI-FASAL",
        "scheme_name": "Meri Fasal Mera Byora (Haryana)",
        "description": "Farmers registering crops on the portal receive ₹10/acre incentive plus priority access to MSP procurement, scheme benefits and insurance.",
        "crop_required": "any",
        "min_land_hectares": 0.1,
        "max_land_hectares": 50.0,
        "max_income": 1_500_000.0,
        "eligible_states": ["Haryana"],
        "benefit_amount": 2500.0,
        "scheme_type": "state",
        "ministry": "Haryana Agriculture Department",
        "category": "marketing",
        "source_url": "https://fasal.haryana.gov.in",
    },
    {
        "scheme_id": "S-HR-YANTRA-ANUDAAN",
        "scheme_name": "Haryana Krishi Yantra Anudaan",
        "description": "40–50% subsidy on agricultural machinery for Haryana farmers via Direct Benefit Transfer. Apply through Agri Department portal.",
        "crop_required": "any",
        "min_land_hectares": 0.5,
        "max_land_hectares": 15.0,
        "max_income": 900_000.0,
        "eligible_states": ["Haryana"],
        "benefit_amount": 30000.0,
        "scheme_type": "state",
        "ministry": "Haryana Agriculture Department",
        "category": "mechanization",
        "source_url": "https://agriharyana.gov.in",
    },
    # ---- Rajasthan ----------------------------------------------------------
    {
        "scheme_id": "S-RJ-KISAN-MITRA-URJA",
        "scheme_name": "Mukhyamantri Kisan Mitra Urja Yojana (Rajasthan)",
        "description": "₹1,000/month electricity subsidy (max ₹12,000/year) for agricultural consumers in Rajasthan. Benefit transferred directly to farmer bank accounts.",
        "crop_required": "any",
        "min_land_hectares": 0.1,
        "max_land_hectares": 50.0,
        "max_income": 1_000_000.0,
        "eligible_states": ["Rajasthan"],
        "benefit_amount": 12000.0,
        "scheme_type": "state",
        "ministry": "Rajasthan Energy Department",
        "category": "subsidy",
        "source_url": "https://agriculture.rajasthan.gov.in",
    },
    {
        "scheme_id": "S-RJ-CROP-INPUT-SUBSIDY",
        "scheme_name": "Rajasthan Fasal Bigad Anudan Yojana",
        "description": "Input cost subsidy for Rajasthan farmers when crop loss exceeds 50% due to drought, flood or hailstorm — ₹6,800–₹13,500/ha.",
        "crop_required": "any",
        "min_land_hectares": 0.1,
        "max_land_hectares": 10.0,
        "max_income": 700_000.0,
        "eligible_states": ["Rajasthan"],
        "benefit_amount": 10000.0,
        "scheme_type": "state",
        "ministry": "Rajasthan Agriculture Department",
        "category": "disaster_relief",
        "source_url": "https://agriculture.rajasthan.gov.in",
    },
    # ---- Uttar Pradesh ------------------------------------------------------
    {
        "scheme_id": "S-UP-KISAN-KARJ-RAHAT",
        "scheme_name": "UP Kisan Rin Mochan Yojana (Loan Waiver)",
        "description": "One-time crop loan waiver up to ₹1 lakh for small and marginal farmers in Uttar Pradesh with outstanding short-term agriculture loans.",
        "crop_required": "any",
        "min_land_hectares": 0.0,
        "max_land_hectares": 2.0,
        "max_income": 500_000.0,
        "eligible_states": ["Uttar Pradesh"],
        "benefit_amount": 100000.0,
        "scheme_type": "state",
        "ministry": "UP Agriculture Department",
        "category": "credit",
        "source_url": "https://upagripardarshi.gov.in",
    },
    {
        "scheme_id": "S-UP-AGRI-EQUIPMENT",
        "scheme_name": "UP Agricultural Equipment Subsidy",
        "description": "50% subsidy (max ₹60,000) for SC/ST farmers and 25–40% for others on purchase of power tillers, threshers, tractors and other farm machinery.",
        "crop_required": "any",
        "min_land_hectares": 0.25,
        "max_land_hectares": 20.0,
        "max_income": 900_000.0,
        "eligible_states": ["Uttar Pradesh"],
        "benefit_amount": 35000.0,
        "scheme_type": "state",
        "ministry": "UP Agriculture Department",
        "category": "mechanization",
        "source_url": "https://upagripardarshi.gov.in",
    },
    # ---- Madhya Pradesh -----------------------------------------------------
    {
        "scheme_id": "S-MP-KISAN-KALYAN",
        "scheme_name": "Mukhyamantri Kisan Kalyan Yojana (MP)",
        "description": "Additional ₹4,000/year income support for PM-KISAN beneficiaries in Madhya Pradesh. Two instalments of ₹2,000 each.",
        "crop_required": "any",
        "min_land_hectares": 0.0,
        "max_land_hectares": 100.0,
        "max_income": 1_500_000.0,
        "eligible_states": ["Madhya Pradesh"],
        "benefit_amount": 4000.0,
        "scheme_type": "state",
        "ministry": "MP Agriculture Department",
        "category": "income_support",
        "source_url": "https://farmer.mponline.gov.in",
    },
    {
        "scheme_id": "S-MP-YANTRA-ANUDAAN",
        "scheme_name": "MP Krishi Yantra Anudaan Yojana",
        "description": "40–50% subsidy for SC/ST and women farmers; 30–40% for others on 44 types of farm equipment. Applications via MP e-Krishi portal.",
        "crop_required": "any",
        "min_land_hectares": 0.25,
        "max_land_hectares": 20.0,
        "max_income": 900_000.0,
        "eligible_states": ["Madhya Pradesh"],
        "benefit_amount": 30000.0,
        "scheme_type": "state",
        "ministry": "MP Agriculture Department",
        "category": "mechanization",
        "source_url": "https://farmer.mponline.gov.in",
    },
    # ---- Gujarat ------------------------------------------------------------
    {
        "scheme_id": "S-GJ-KISAN-SAHAY",
        "scheme_name": "Mukhyamantri Kisan Sahay Yojana (Gujarat)",
        "description": "₹20,000/ha (33–60% crop loss) or ₹25,000/ha (>60% loss) compensation for Gujarat farmers hit by drought, excess rain or unseasonal rain.",
        "crop_required": "any",
        "min_land_hectares": 0.1,
        "max_land_hectares": 4.0,
        "max_income": 700_000.0,
        "eligible_states": ["Gujarat"],
        "benefit_amount": 20000.0,
        "scheme_type": "state",
        "ministry": "Gujarat Agriculture Department",
        "category": "disaster_relief",
        "source_url": "https://agr.gujarat.gov.in",
    },
    {
        "scheme_id": "S-GJ-SOIL-HEALTH",
        "scheme_name": "Gujarat Micro-Nutrient Subsidy Scheme",
        "description": "50% subsidy on micronutrient fertilisers (zinc, boron, sulphur) for Gujarat farmers based on soil health card recommendations.",
        "crop_required": "any",
        "min_land_hectares": 0.25,
        "max_land_hectares": 20.0,
        "max_income": 800_000.0,
        "eligible_states": ["Gujarat"],
        "benefit_amount": 3000.0,
        "scheme_type": "state",
        "ministry": "Gujarat Agriculture Department",
        "category": "subsidy",
        "source_url": "https://agr.gujarat.gov.in",
    },
    # ---- West Bengal --------------------------------------------------------
    {
        "scheme_id": "S-WB-KRISHAK-BANDHU",
        "scheme_name": "Bangla Krishak Bandhu (West Bengal)",
        "description": "₹10,000/year (2 acres+) or ₹5,000/year (below 2 acres) input support for West Bengal farmers plus ₹2 lakh life insurance cover.",
        "crop_required": "any",
        "min_land_hectares": 0.0,
        "max_land_hectares": 100.0,
        "max_income": 1_500_000.0,
        "eligible_states": ["West Bengal"],
        "benefit_amount": 10000.0,
        "scheme_type": "state",
        "ministry": "West Bengal Agriculture Department",
        "category": "income_support",
        "source_url": "https://krishakbandhu.net",
    },
    # ---- Odisha -------------------------------------------------------------
    {
        "scheme_id": "S-OD-KALIA",
        "scheme_name": "KALIA Scheme (Odisha)",
        "description": "₹25,000 comprehensive livelihood support (₹10,000 crop input + ₹12,500 horticulture/livestock + ₹2,000 vulnerable assistance) for small/marginal farmers.",
        "crop_required": "any",
        "min_land_hectares": 0.0,
        "max_land_hectares": 2.0,
        "max_income": 500_000.0,
        "eligible_states": ["Odisha"],
        "benefit_amount": 25000.0,
        "scheme_type": "state",
        "ministry": "Odisha Agriculture Department",
        "category": "income_support",
        "source_url": "https://kalia.odisha.gov.in",
    },
    {
        "scheme_id": "S-OD-BALARAM",
        "scheme_name": "Balaram Yojana (Odisha)",
        "description": "Crop loans at 0% interest for landless/tenant farmers and SHG members via micro-credit and self-help groups.",
        "crop_required": "any",
        "min_land_hectares": 0.0,
        "max_land_hectares": 2.0,
        "max_income": 400_000.0,
        "eligible_states": ["Odisha"],
        "benefit_amount": 10000.0,
        "scheme_type": "state",
        "ministry": "Odisha Agriculture Department",
        "category": "credit",
        "source_url": "https://odishaagri.nic.in",
    },
    # ---- Jharkhand ----------------------------------------------------------
    {
        "scheme_id": "S-JH-KRISHI-ASHIRWAD",
        "scheme_name": "Mukhyamantri Krishi Ashirwad Yojana (Jharkhand)",
        "description": "₹5,000/acre per year (up to 5 acres) investment support for marginal farmers in Jharkhand. Paid before kharif season.",
        "crop_required": "any",
        "min_land_hectares": 0.0,
        "max_land_hectares": 2.0,
        "max_income": 400_000.0,
        "eligible_states": ["Jharkhand"],
        "benefit_amount": 12500.0,
        "scheme_type": "state",
        "ministry": "Jharkhand Agriculture Department",
        "category": "income_support",
        "source_url": "https://mmkay.jharkhand.gov.in",
    },
    # ---- Bihar --------------------------------------------------------------
    {
        "scheme_id": "S-BR-RAJYA-FASAL-SAHAYATA",
        "scheme_name": "Bihar Rajya Fasal Sahayata Yojana",
        "description": "State-funded crop damage compensation: ₹7,500/ha for 20–30% loss and ₹10,000/ha for >30% crop loss. Free enrollment, no premium.",
        "crop_required": "any",
        "min_land_hectares": 0.1,
        "max_land_hectares": 5.0,
        "max_income": 600_000.0,
        "eligible_states": ["Bihar"],
        "benefit_amount": 10000.0,
        "scheme_type": "state",
        "ministry": "Bihar Cooperative Department",
        "category": "insurance",
        "source_url": "https://pacsonline.bih.nic.in/fsy",
    },
    {
        "scheme_id": "S-BR-DIESEL-ANUDAN",
        "scheme_name": "Bihar Diesel Anudan Yojana",
        "description": "₹60/litre diesel subsidy for irrigation pumps (max 8 litres/acre per season) for Bihar farmers without electricity connection.",
        "crop_required": "any",
        "min_land_hectares": 0.1,
        "max_land_hectares": 4.0,
        "max_income": 500_000.0,
        "eligible_states": ["Bihar"],
        "benefit_amount": 3000.0,
        "scheme_type": "state",
        "ministry": "Bihar Agriculture Department",
        "category": "subsidy",
        "source_url": "https://dbtagriculture.bihar.gov.in",
    },
    # ---- Chhattisgarh -------------------------------------------------------
    {
        "scheme_id": "S-CG-RAJIV-KISAN-NYAY",
        "scheme_name": "Rajiv Gandhi Kisan Nyay Yojana (Chhattisgarh)",
        "description": "₹9,000/acre input subsidy for paddy farmers in Chhattisgarh. Covers kharif crop cycle with direct bank transfer.",
        "crop_required": "rice",
        "min_land_hectares": 0.1,
        "max_land_hectares": 10.0,
        "max_income": 800_000.0,
        "eligible_states": ["Chhattisgarh"],
        "benefit_amount": 22500.0,
        "scheme_type": "state",
        "ministry": "Chhattisgarh Agriculture Department",
        "category": "income_support",
        "source_url": "https://kisan.cg.gov.in",
    },
    # ---- Kerala -------------------------------------------------------------
    {
        "scheme_id": "S-KL-KARSHAKA-KSHEMASENA",
        "scheme_name": "Kerala Karshaka Kshemasena (Farmer Welfare Fund)",
        "description": "Accident insurance of ₹1 lakh and crop loss compensation for Kerala farmers. Welfare pension of ₹1,100/month for aged farmers.",
        "crop_required": "any",
        "min_land_hectares": 0.0,
        "max_land_hectares": 10.0,
        "max_income": 600_000.0,
        "eligible_states": ["Kerala"],
        "benefit_amount": 15000.0,
        "scheme_type": "state",
        "ministry": "Kerala Agriculture Department",
        "category": "insurance",
        "source_url": "https://keralaagriculture.gov.in",
    },
    {
        "scheme_id": "S-KL-SUBHIKSHA-KERALAM",
        "scheme_name": "Subhiksha Keralam (Kerala)",
        "description": "₹2,500–₹5,000/ha incentive for Kerala farmers who convert fallow land to paddy or vegetable cultivation under state food security mission.",
        "crop_required": "rice",
        "min_land_hectares": 0.1,
        "max_land_hectares": 5.0,
        "max_income": 700_000.0,
        "eligible_states": ["Kerala"],
        "benefit_amount": 5000.0,
        "scheme_type": "state",
        "ministry": "Kerala Agriculture Department",
        "category": "production_support",
        "source_url": "https://keralaagriculture.gov.in",
    },
    # ---- Assam --------------------------------------------------------------
    {
        "scheme_id": "S-AS-CM-KRISHI-SA-SAJULI",
        "scheme_name": "CM Krishi Sa-Sajuli Yojana (Assam)",
        "description": "Free farm equipment kit (hand-operated tools, spray pumps, hand-held implements) worth ₹5,000 to Assam farmers via direct delivery.",
        "crop_required": "any",
        "min_land_hectares": 0.0,
        "max_land_hectares": 2.0,
        "max_income": 400_000.0,
        "eligible_states": ["Assam"],
        "benefit_amount": 5000.0,
        "scheme_type": "state",
        "ministry": "Assam Agriculture Department",
        "category": "mechanization",
        "source_url": "https://agri.assam.gov.in",
    },
    # ---- Himachal Pradesh ---------------------------------------------------
    {
        "scheme_id": "S-HP-KISAN-UTHAN",
        "scheme_name": "Himachal Pradesh Kisan Uthan Yojana",
        "description": "₹1,500/bigha (≈₹9,000/ha) crop production incentive for apple, mango, and vegetable growers in HP. Encourages commercial horticulture.",
        "crop_required": "horticulture",
        "min_land_hectares": 0.1,
        "max_land_hectares": 5.0,
        "max_income": 600_000.0,
        "eligible_states": ["Himachal Pradesh"],
        "benefit_amount": 9000.0,
        "scheme_type": "state",
        "ministry": "HP Horticulture Department",
        "category": "horticulture",
        "source_url": "https://hpagrisnet.gov.in",
    },
]

ALL_SCHEMES: list[dict[str, Any]] = CENTRAL_SCHEMES + STATE_SCHEMES


# ---------------------------------------------------------------------------
# Live scraper (best-effort — failures are silently skipped)
# ---------------------------------------------------------------------------

def _scrape_farmer_portal() -> list[dict[str, Any]]:
    """Try to scrape scheme names/URLs from farmer.gov.in."""
    try:
        import httpx
        from bs4 import BeautifulSoup

        headers = {"User-Agent": "Mozilla/5.0 (compatible; AgriSchemeBot/1.0)"}
        r = httpx.get("https://farmer.gov.in/SchemeList.aspx", headers=headers, timeout=15)
        if r.status_code != 200:
            return []

        soup = BeautifulSoup(r.text, "html.parser")
        scraped: list[dict[str, Any]] = []

        for link in soup.find_all("a", href=True):
            text = link.get_text(strip=True)
            href = link["href"]
            if len(text) < 10 or len(text) > 200:
                continue
            if not any(kw in text.lower() for kw in ["scheme", "yojana", "mission", "krishi", "kisan", "fasal"]):
                continue
            scheme_id = "S-WEB-" + re.sub(r"[^A-Z0-9]", "-", text.upper())[:30]
            scraped.append({
                "scheme_id": scheme_id,
                "scheme_name": text,
                "description": f"Government scheme: {text}. Visit source URL for eligibility details.",
                "crop_required": "any",
                "min_land_hectares": 0.0,
                "max_land_hectares": 100.0,
                "max_income": 1_500_000.0,
                "eligible_states": [],
                "benefit_amount": 0.0,
                "scheme_type": "central",
                "ministry": "Ministry of Agriculture & Farmers Welfare",
                "category": "other",
                "source_url": href if href.startswith("http") else f"https://farmer.gov.in/{href}",
            })

        log.info("farmer.gov.in scrape: found %d scheme links", len(scraped))
        return scraped[:20]
    except Exception as exc:
        log.warning("farmer.gov.in scrape failed (non-critical): %s", exc)
        return []


def _scrape_agricoop() -> list[dict[str, Any]]:
    """Try to scrape scheme list from agricoop.nic.in."""
    try:
        import httpx
        from bs4 import BeautifulSoup

        headers = {"User-Agent": "Mozilla/5.0 (compatible; AgriSchemeBot/1.0)"}
        r = httpx.get("https://agricoop.nic.in/en/schemes", headers=headers, timeout=15)
        if r.status_code != 200:
            return []

        soup = BeautifulSoup(r.text, "html.parser")
        scraped: list[dict[str, Any]] = []

        for item in soup.find_all(["h3", "h4", "li", "a"]):
            text = item.get_text(strip=True)
            if len(text) < 15 or len(text) > 150:
                continue
            if not any(kw in text.lower() for kw in ["scheme", "yojana", "mission", "programme"]):
                continue
            scheme_id = "S-AC-" + re.sub(r"[^A-Z0-9]", "-", text.upper())[:25]
            scraped.append({
                "scheme_id": scheme_id,
                "scheme_name": text,
                "description": f"Central agricultural scheme: {text}. Check agricoop.nic.in for eligibility.",
                "crop_required": "any",
                "min_land_hectares": 0.0,
                "max_land_hectares": 100.0,
                "max_income": 1_500_000.0,
                "eligible_states": [],
                "benefit_amount": 0.0,
                "scheme_type": "central",
                "ministry": "Ministry of Agriculture & Farmers Welfare",
                "category": "other",
                "source_url": "https://agricoop.nic.in/en/schemes",
            })

        log.info("agricoop.nic.in scrape: found %d items", len(scraped))
        return scraped[:15]
    except Exception as exc:
        log.warning("agricoop.nic.in scrape failed (non-critical): %s", exc)
        return []


def fetch_all_schemes() -> list[dict[str, Any]]:
    """Return merged list: hardcoded verified schemes + live-scraped extras.

    Hardcoded schemes always win over scraped duplicates (by scheme_id).
    """
    hardcoded_ids = {s["scheme_id"] for s in ALL_SCHEMES}

    live: list[dict[str, Any]] = []
    live += _scrape_farmer_portal()
    live += _scrape_agricoop()

    # Deduplicate live-scraped by scheme_id, skip if conflicts with hardcoded
    seen: set[str] = set(hardcoded_ids)
    deduped_live: list[dict[str, Any]] = []
    for s in live:
        if s["scheme_id"] not in seen and s["scheme_name"] not in {h["scheme_name"] for h in ALL_SCHEMES}:
            seen.add(s["scheme_id"])
            deduped_live.append(s)

    log.info("Schemes: %d hardcoded + %d live-scraped = %d total",
             len(ALL_SCHEMES), len(deduped_live), len(ALL_SCHEMES) + len(deduped_live))
    return ALL_SCHEMES + deduped_live


def upsert_schemes(scheme_list: list[dict[str, Any]]) -> int:
    """Upsert schemes into MongoDB. Returns count upserted."""
    from ..db import schemes as schemes_col

    count = 0
    for s in scheme_list:
        schemes_col.update_one(
            {"scheme_id": s["scheme_id"]},
            {"$set": {**s, "updated_at": datetime.now(timezone.utc)}},
            upsert=True,
        )
        count += 1
    return count
